# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TestFlight/README.md
name: TestFlight
sources:
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/TestFlight/TestFlight.list
