# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HBOUSA/README.md
name: HBOUSA
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/HBO.list
  - https://raw.githubusercontent.com/luuanng/surge/main/HBOUSA.list
