# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/CCTV/README.md
name: CCTV
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CCTV.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CCTV.list
