# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YouTubeMusic/README.md
name: YouTubeMusic
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTubeMusic.yaml
