# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LondonReal/README.md
name: LondonReal
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/LondonReal.list
