# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/XiaoGouKeJi/README.md
name: XiaoGouKeJi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/XiaoGouKeJi.list
