# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/6JianFang/README.md
name: 6JianFang
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/6JianFang.list
