# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Verisign/README.md
name: Verisign
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Verisign.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Verisign.yaml
