# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ProxyLite/README.md
name: ProxyLite
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Outside.list
  - https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Proxy.yaml
