# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Origin/README.md
name: Origin
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Origin.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
