# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TigerFintech/README.md
name: TigerFintech
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/TigerFintech.list
