# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Douyu/README.md
name: Douyu
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Douyu.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DouYu.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Douyu.yaml
