# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/AmazonPrimeVideo/README.md
name: AmazonPrimeVideo
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/AmazonPrimeVideo.list
