# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Sina/README.md
name: Sina
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sina.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/Weibo/Weibo.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Sina.list
