# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/WildRift/README.md
name: WildRift
sources:
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Games/WildRift.list
