# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Razer/README.md
name: Razer
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Razer.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Razer.yaml
