# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Olevod/README.md
name: Olevod
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Olevod.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Olevod.list
