# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Zoho/README.md
name: Zoho
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Zoho.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Zoho.yaml
