# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TeamViewer/README.md
name: TeamViewer
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TeamViewer.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TeamViewer.yaml
