# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DiDi/README.md
name: DiDi
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DiDi.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DiDi.list
