# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Python/README.md
name: Python
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Python.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Python.yaml
