# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/China/README.md
name: China
sources:
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Basic/CN.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/China/China.list
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Mainland.list
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Region/China.list
  - https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Domestic.yaml
  - https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rules/Mainland.list
