# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Tencent/README.md
name: Tencent
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Tencent.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Tencent.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Tencent.yaml
