# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/KuaiDi100/README.md
name: KuaiDi100
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/KuaiDi100.list
