# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ShiNongZhiKe/README.md
name: ShiNongZhiKe
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ShiNongZhiKe.list
