# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Dailymotion/README.md
name: Dailymotion
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Dailymotion.list
