# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ViuTV/README.md
name: ViuTV
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/ViuTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ViuTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/ViuTV.yaml
