# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/BBC/README.md
name: BBC
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BBC.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/BBC.list
