# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HKBN/README.md
name: HKBN
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/HKBN.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/HKBN.yaml
