# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/BiliBili/README.md
name: BiliBili
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BiliBili.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml
  - https://ruleset.isagood.day/bilibili.conf
