# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ShangHaiJuXiao/README.md
name: ShangHaiJuXiao
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ShangHaiJuXiao.list
