# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LiTV/README.md
name: LiTV
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/LiTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/LiTV.list
