# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Kingsoft/README.md
name: Kingsoft
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Kingsoft.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Kingsoft.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Kingsoft.yaml
