# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YunFanJiaSu/README.md
name: YunFanJiaSu
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/YunFanJiaSu.list
