# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/GoogleEarth/README.md
name: GoogleEarth
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleEarth.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleEarth.yaml
