# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/KouDaiShiShang/README.md
name: KouDaiShiShang
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/KouDaiShiShang.list
