# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Jsdelivr/README.md
name: Jsdelivr
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Jsdelivr.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Jsdelivr.yaml
