# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/FengHuangWang/README.md
name: FengHuangWang
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/FengHuangWang.list
