# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TIDAL/README.md
name: TIDAL
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/TIDAL.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TIDAL.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TIDAL.yaml
