# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Canon/README.md
name: Canon
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Canon.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Canon.yaml
