# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ZhiYinManKe/README.md
name: ZhiYinManKe
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ZhiYinManKe.list
