# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Teambition/README.md
name: Teambition
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Teambition.list
