# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Acer/README.md
name: Acer
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Acer.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Acer.yaml
