# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Nintendo/README.md
name: Nintendo
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/Nintendo.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Nintendo.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
