# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TaiheMusic/README.md
name: TaiheMusic
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/TaiheMusic.list
