# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LivePerson/README.md
name: LivePerson
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/LivePerson.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/LivePerson.yaml
