# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LvMiLianChuang/README.md
name: LvMiLianChuang
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/LvMiLianChuang.list
