# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TapTap/README.md
name: TapTap
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TapTap.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TapTap.yaml
