# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/FOXNOW/README.md
name: FOXNOW
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/FoxNow.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/FoxNow.yaml
