# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/PikPak/README.md
name: PikPak
sources:
  - https://raw.githubusercontent.com/tugepaopao/Image-Storage/master/rule/QuantumultX/pikpak.list
