# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Akamai/README.md
name: Akamai
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Akamai.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Akamai.yaml
