# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Dropbox/README.md
name: Dropbox
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Dropbox.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Dropbox.yaml
