# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Bahamut/README.md
name: Bahamut
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Bahamut.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bahamut.yaml
