# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/McDonalds/README.md
name: McDonalds
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/McDonalds.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/McDonalds.yaml
