# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Discord/README.md
name: Discord
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Discord.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Discord.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Discord.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Discord.yaml
