# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ChinaUnicom/README.md
name: ChinaUnicom
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaUnicom.list
