# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/58TongCheng/README.md
name: 58TongCheng
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/58TongCheng.list
