# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Baidu/README.md
name: Baidu
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Baidu.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/BaiDu.list
