# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Pixnet/README.md
name: Pixnet
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Pixnet.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Pixnet.yaml
