# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TencentVideo/README.md
name: TencentVideo
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TencentVideo.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TencentVideo.yaml
