# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/JinJiangWenXue/README.md
name: JinJiangWenXue
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/JinJiangWenXue.list
