# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/GitHub/README.md
name: GitHub
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Github.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Github.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Github.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Github.yaml
