# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/PBS/README.md
name: PBS
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/PBS.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PBS.list
