# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Cloudflare/README.md
name: Cloudflare
sources:
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Cloudflare.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Cloudflare.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Cloudflare.yaml
