# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DingXiangYuan/README.md
name: DingXiangYuan
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DingXiangYuan.list
