# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Gettyimages/README.md
name: Gettyimages
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Gettyimages.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Gettyimages.yaml
