# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/WangXinKeJi/README.md
name: WangXinKeJi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/WangXinKeJi.list
