# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LastPass/README.md
name: LastPass
sources:
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/App/tools/LastPass.list
