# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YouTube/README.md
name: YouTube
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Optional/YouTube.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/YouTube.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
