# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/NaSDDNS/README.md
name: NaSDDNS
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/NaSDDNS.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NaSDDNS.list
