# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Apple/README.md
name: Apple
sources:
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/AppStore/AppStore.list
  - https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/icloud.txt
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/TestFlight/TestFlight.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleNews.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AppleTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Apple.list
  - https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/apple.txt
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Apple.list
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Apple.list
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Basic/Apple-proxy.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/AppleBlock/AppleBlock.list
  - https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
  - https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
  - https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Apple.yaml
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple/AppleFirmware.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple/AppleHardware.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple/AppleMedia.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml
  - https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rules/Apple.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/AppleNews.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/AppleTV.yaml
