# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ZhongGuoShiHua/README.md
name: ZhongGuoShiHua
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ZhongGuoShiHua.list
