# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/MeiTu/README.md
name: MeiTu
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Meitu.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Meitu.yaml
