# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Dubox/README.md
name: Dubox
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Dubox.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Dubox.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Dubox.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Dubox.yaml
