# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/PayPal/README.md
name: PayPal
sources:
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Optional/PayPal.list
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Paypal.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/PayPal.list
  - https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/PayPal.yaml
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/PayPal.yaml
