# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DianCeWangKe/README.md
name: DianCeWangKe
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DianCeWangKe.list
