# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/IBM/README.md
name: IBM
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/IBM.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/IBM.yaml
