# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Wikipedia/README.md
name: Wikipedia
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Wikipedia.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Wikipedia.yaml
