# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HaiNanHangKong/README.md
name: HaiNanHangKong
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/HaiNanHangKong.list
