# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/PPTV/README.md
name: PPTV
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/PPTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PPTVPPLive.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/PPTVPPLive.yaml
