# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Xbox/README.md
name: Xbox
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game/Xbox.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xbox.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Xbox.yaml
