# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Netflix/README.md
name: Netflix
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
  - https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Optional/Netflix.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list
  - https://raw.githubusercontent.com/QiuSimons/Netflix_IP/master/getflix.txt
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetflixIP.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml
  - https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rules/Netflix.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/NetflixIP.yaml
