# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/XiaoMi/README.md
name: XiaoMi
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/MI.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Xiaomi.list
