# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Japonx/README.md
name: Japonx
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Japonx.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Japonx.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Japonx.yaml
