# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Himalaya/README.md
name: Himalaya
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Ximalaya.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/XiMaLaYa.list
