# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YiXiaKeJi/README.md
name: YiXiaKeJi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/YiXiaKeJi.list
