# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LeTV/README.md
name: LeTV
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/LeTV.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/LeTV.list
