# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Line/README.md
name: Line
sources:
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/SNS/Line.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Line.list
