# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ZhiYunZhong/README.md
name: ZhiYunZhong
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ZhiYunZhong.list
