# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/LanZouYun/README.md
name: LanZouYun
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/LanZouYun.list
