# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DiSiFanShi/README.md
name: DiSiFanShi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DiSiFanShi.list
