# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Dynu/README.md
name: Dynu
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Dynu.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Dynu.yaml
