# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/MIUIPrivacy/README.md
name: MIUIPrivacy
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/MIUIPrivacy.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/MIUIPrivacy.list
