# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DiLianWangLuo/README.md
name: DiLianWangLuo
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/DiLianWangLuo.list
