# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Jetbrains/README.md
name: Jetbrains
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Jetbrains.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Jetbrains.yaml
