# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/CaiXinChuanMei/README.md
name: CaiXinChuanMei
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/CaiXinChuanMei.list
