# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Imgur/README.md
name: Imgur
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Imgur.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Imgur.yaml
