# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Adidas/README.md
name: Adidas
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Adidas.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Adidas.yaml
