# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Advertising/README.md
name: Advertising
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
  - https://raw.githubusercontent.com/NobyDa/ND-AD/master/Surge/AD_Block.txt
  - https://raw.githubusercontent.com/NobyDa/Script/master/Surge/AdRule.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/Advertising/Advertising.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/Advertising/LianXiangJia/LianXiangJia.list
  - https://raw.githubusercontent.com/scomper/surge-list/master/reject.list
  - https://raw.githubusercontent.com/scomper/surge-list/master/adblock.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
  - https://raw.githubusercontent.com/limbopro/Adblock4limbo/main/Adblock4limbo.list
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Custom/ad-domains.list
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Custom/video-ad.list
  - https://raw.githubusercontent.com/an0na/R/master/Filter/AdBlock.list
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Advertising/AdReject.list
  - https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Advertising/Hijacking.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
  - https://raw.githubusercontent.com/yjqiang/surge_scripts/main/modules/hupu/hupu.sgmodule
  - https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
  - https://raw.githubusercontent.com/zqzess/rule_for_quantumultX/master/QuantumultX/rules/AdBlock.list
