# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Opera/README.md
name: Opera
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Opera.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Opera.yaml
