# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HBO/README.md
name: HBO
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/HBO.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HBO.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/HBO.yaml
