# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/WeiZhiYunDong/README.md
name: WeiZhiYunDong
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/WeiZhiYunDong.list
