# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ZhongYuanYiShang/README.md
name: ZhongYuanYiShang
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ZhongYuanYiShang.list
