# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/KugouKuwo/README.md
name: KugouKuwo
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/Kugou%26Kuwo.list
