# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Direct/README.md
name: Direct
sources:
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/WhiteList/WhiteList.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/PublicDirectCDN.list
