# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Blued/README.md
name: Blued
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Blued.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Blued.yaml
