# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Apkpure/README.md
name: Apkpure
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Apkpure.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Apkpure.yaml
