# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/WanKaHuanJu/README.md
name: WanKaHuanJu
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/WanKaHuanJu.list
