# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HibyMusic/README.md
name: HibyMusic
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/HibyMusic.list
