# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Niconico/README.md
name: Niconico
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Niconico.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Niconico.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Niconico.yaml
