# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YuanFuDao/README.md
name: YuanFuDao
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/YuanFuDao.list
