# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/SublimeText/README.md
name: SublimeText
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/SublimeText.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/SublimeText.yaml
