# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Spark/README.md
name: Spark
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spark.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Spark.yaml
