# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/QingCloud/README.md
name: QingCloud
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/QingCloud.list
