# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/AppleHardware/README.md
name: AppleHardware
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple/AppleHardware.list
