"""
Mihomo rule-provider YAML emitter.

Behavior detection:
  domain   — all rules are DOMAIN / DOMAIN-SUFFIX / DOMAIN-KEYWORD
             → supports .mrs binary via `mihomo convert-ruleset`
  ipcidr   — all rules are IP-CIDR / IP-CIDR6
             → supports .mrs binary
  classical — mixed types or contains DOMAIN-REGEX / PROCESS-NAME
             → YAML only, no binary

Reference: https://wiki.metacubex.one/en_US/config/rule-providers/
"""

from __future__ import annotations

DOMAIN_TYPES = {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD"}
IPCIDR_TYPES = {"IP-CIDR", "IP-CIDR6", "IP6-CIDR"}
CLASSICAL_ONLY_TYPES = {"DOMAIN-REGEX", "PROCESS-NAME"}


def detect_behavior(rules: list[tuple[str, str]]) -> str:
    """Return 'domain', 'ipcidr', or 'classical'."""
    types = {rt for rt, _ in rules}
    if not types:
        return "classical"
    if types <= DOMAIN_TYPES:
        return "domain"
    if types <= IPCIDR_TYPES:
        return "ipcidr"
    return "classical"


def to_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit mihomo rule-provider compatible YAML.
    Duplicate (type, value) pairs are removed; order is preserved on first occurrence.
    """
    seen: set[tuple[str, str]] = set()
    deduped: list[tuple[str, str]] = []
    for item in rules:
        if item not in seen:
            seen.add(item)
            deduped.append(item)

    lines = [
        f"# {category} — generated by hajimihomo",
        f"# rules: {len(deduped)}",
        "payload:",
    ]
    for rule_type, value in deduped:
        lines.append(f"  - {rule_type},{value}")
    lines.append("")  # trailing newline
    return "\n".join(lines)
