"""
Mihomo rule-provider YAML emitter.

Behavior detection:
  domain   — all rules are DOMAIN / DOMAIN-SUFFIX only
             → supports .mrs binary via `mihomo convert-ruleset`
  ipcidr   — all rules are IP-CIDR / IP-CIDR6 only
             → supports .mrs binary
  classical — anything else (DOMAIN-KEYWORD, DOMAIN-REGEX, PROCESS-NAME, IP-ASN, or mixed)
             → YAML only, no binary

Split files (emitted only for classical-behavior categories):
  .domain.yaml    — DOMAIN + DOMAIN-SUFFIX only        (behavior:domain)
  .ip.yaml        — IP-CIDR rules WITH no-resolve      (behavior:ipcidr, safe anywhere)
  .ip-resolve.yaml— IP-CIDR rules WITHOUT no-resolve   (behavior:ipcidr, MUST load last)
  .residual.yaml  — DOMAIN-KEYWORD + DOMAIN-REGEX + IP-ASN (behavior:classical)
  .process.yaml   — PROCESS-NAME only                  (behavior:classical)

Consumer contract:
  .ip.yaml       must be referenced with no-resolve in the rule-set entry (safe; no DNS)
  .ip-resolve.yaml must be loaded LAST — will trigger DNS for unmatched requests
  .residual.yaml may contain IP-ASN,<asn>,no-resolve (classical format); safe to load
                 before ip-resolve but after .domain if DNS triggering is a concern.

Do NOT combine the all-in-one Tier-1 .yaml with split files — rules would be applied twice.

Reference: https://wiki.metacubex.one/en_US/config/rule-providers/
"""

from __future__ import annotations

# Only DOMAIN + DOMAIN-SUFFIX are valid in behavior:domain
DOMAIN_BEHAVIOR_TYPES = {"DOMAIN", "DOMAIN-SUFFIX"}
IPCIDR_TYPES = {"IP-CIDR", "IP-CIDR6", "IP6-CIDR"}
RESIDUAL_TYPES = {"DOMAIN-KEYWORD", "DOMAIN-REGEX", "IP-ASN"}
PROCESS_TYPES = {"PROCESS-NAME"}


def detect_behavior(rules: list[tuple[str, str]]) -> str:
    """Return 'domain', 'ipcidr', or 'classical'."""
    types = {rt for rt, _ in rules}
    if not types:
        return "classical"
    if types <= DOMAIN_BEHAVIOR_TYPES:
        return "domain"
    if types <= IPCIDR_TYPES:
        return "ipcidr"
    return "classical"


def _dedup(rules: list[tuple[str, str]]) -> list[tuple[str, str]]:
    seen: set[tuple[str, str]] = set()
    out: list[tuple[str, str]] = []
    for item in rules:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def to_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit mihomo rule-provider YAML for the detected behavior.

    - behavior:domain  → bare 'example.com' / '.example.com' format
    - behavior:ipcidr  → bare CIDR strings
    - behavior:classical → RULE_TYPE,VALUE format (all types)
    """
    behavior = detect_behavior(rules)
    deduped = _dedup(rules)

    # Per-type stats for header
    type_counts: dict[str, int] = {}
    for rt, _ in deduped:
        type_counts[rt] = type_counts.get(rt, 0) + 1
    stats = "  ".join(f"{rt.lower()}:{n}" for rt, n in sorted(type_counts.items()))

    header = [
        f"# {category} — generated by hajimihomo",
        f"# behavior: {behavior}  rules: {len(deduped)}  ({stats})",
        "payload:",
    ]

    if behavior == "domain":
        body = _domain_payload(deduped)
    elif behavior == "ipcidr":
        body = _ipcidr_payload(deduped)
    else:
        body = _classical_payload(deduped)

    return "\n".join(header + body) + "\n"


def to_domain_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit a domain-behavior YAML containing only DOMAIN / DOMAIN-SUFFIX rules.
    Returns empty string if no domain rules exist.
    Only emit for classical-behavior categories (split file).
    """
    domain_rules = [(rt, v) for rt, v in rules if rt in DOMAIN_BEHAVIOR_TYPES]
    if not domain_rules:
        return ""
    deduped = _dedup(domain_rules)

    lines = [
        f"# {category} (domain split) — generated by hajimihomo",
        f"# behavior: domain  rules: {len(deduped)}",
        "payload:",
    ] + _domain_payload(deduped) + [""]
    return "\n".join(lines)


def to_ip_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    IP-CIDR/IP-CIDR6 rules that carry the no-resolve flag → behavior:ipcidr.
    Consumer must reference this file with no-resolve; rules do not trigger DNS.
    Returns empty string if no such rules exist.
    """
    ip_rules = [(rt, v) for rt, v in rules if rt in IPCIDR_TYPES and ",no-resolve" in v]
    if not ip_rules:
        return ""
    deduped = _dedup(ip_rules)

    lines = [
        f"# {category} (ip, no-resolve) — generated by hajimihomo",
        f"# behavior: ipcidr  rules: {len(deduped)}",
        "# Load before .ip-resolve files; reference with no-resolve in rule-set entry.",
        "payload:",
    ] + _ipcidr_payload(deduped) + [""]
    return "\n".join(lines)


def to_ip_resolve_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    IP-CIDR/IP-CIDR6 rules WITHOUT no-resolve → behavior:ipcidr.
    These trigger DNS resolution. MUST be loaded last in the rules list.
    Returns empty string if no such rules exist.
    """
    ip_rules = [(rt, v) for rt, v in rules if rt in IPCIDR_TYPES and ",no-resolve" not in v]
    if not ip_rules:
        return ""
    deduped = _dedup(ip_rules)

    lines = [
        f"# {category} (ip-resolve) — generated by hajimihomo",
        f"# behavior: ipcidr  rules: {len(deduped)}",
        "# WARNING: triggers DNS for every unmatched request. MUST be loaded LAST.",
        "payload:",
    ] + _ipcidr_payload(deduped) + [""]
    return "\n".join(lines)


def to_residual_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    DOMAIN-KEYWORD + DOMAIN-REGEX + IP-ASN rules → behavior:classical.
    Load after .domain, before .ip-resolve.
    Returns empty string if no residual rules exist.
    """
    residual = [(rt, v) for rt, v in rules if rt in RESIDUAL_TYPES]
    if not residual:
        return ""
    deduped = _dedup(residual)

    lines = [
        f"# {category} (residual) — generated by hajimihomo",
        f"# behavior: classical  rules: {len(deduped)}",
        "payload:",
    ] + _classical_payload(deduped) + [""]
    return "\n".join(lines)


def to_process_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    PROCESS-NAME rules → behavior:classical.
    Load after .domain to let domain policy win unless explicitly overridden.
    Returns empty string if no process rules exist.
    """
    process = [(rt, v) for rt, v in rules if rt in PROCESS_TYPES]
    if not process:
        return ""
    deduped = _dedup(process)

    lines = [
        f"# {category} (process) — generated by hajimihomo",
        f"# behavior: classical  rules: {len(deduped)}",
        "payload:",
    ] + _classical_payload(deduped) + [""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Format helpers
# ---------------------------------------------------------------------------

def _domain_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:domain lines — bare or dot-prefixed."""
    lines = []
    for rt, v in rules:
        if rt == "DOMAIN":
            lines.append(f"  - '{v}'")
        else:  # DOMAIN-SUFFIX
            lines.append(f"  - '.{v}'")
    return lines


def _ipcidr_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:ipcidr lines — bare CIDR strings, no-resolve stripped."""
    lines = []
    for rt, v in rules:
        cidr = v.removesuffix(",no-resolve")
        lines.append(f"  - '{cidr}'")
    return lines


def _classical_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:classical lines — RULE_TYPE,VALUE format."""
    return [f"  - {rt},{v}" for rt, v in rules]
