"""
Mihomo rule-provider YAML emitter.

Behavior detection:
  domain   — all rules are DOMAIN / DOMAIN-SUFFIX only
             → supports .mrs binary via `mihomo convert-ruleset`
  ipcidr   — all rules are IP-CIDR / IP-CIDR6 only
             → supports .mrs binary
  classical — anything else (DOMAIN-KEYWORD, DOMAIN-REGEX, PROCESS-NAME, or mixed)
             → YAML only, no binary

Note: DOMAIN-KEYWORD is classical-only (not supported by behavior:domain).

Reference: https://wiki.metacubex.one/en_US/config/rule-providers/
"""

from __future__ import annotations

# Only DOMAIN + DOMAIN-SUFFIX are valid in behavior:domain
DOMAIN_BEHAVIOR_TYPES = {"DOMAIN", "DOMAIN-SUFFIX"}
IPCIDR_TYPES = {"IP-CIDR", "IP-CIDR6", "IP6-CIDR"}


def detect_behavior(rules: list[tuple[str, str]]) -> str:
    """Return 'domain', 'ipcidr', or 'classical'."""
    types = {rt for rt, _ in rules}
    if not types:
        return "classical"
    if types <= DOMAIN_BEHAVIOR_TYPES:
        return "domain"
    if types <= IPCIDR_TYPES:
        return "ipcidr"
    return "classical"


def _dedup(rules: list[tuple[str, str]]) -> list[tuple[str, str]]:
    seen: set[tuple[str, str]] = set()
    out: list[tuple[str, str]] = []
    for item in rules:
        if item not in seen:
            seen.add(item)
            out.append(item)
    return out


def to_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit mihomo rule-provider YAML for the detected behavior.

    - behavior:domain  → bare 'example.com' / '.example.com' format
    - behavior:ipcidr  → bare CIDR strings
    - behavior:classical → RULE_TYPE,VALUE format (all types)
    """
    behavior = detect_behavior(rules)
    deduped = _dedup(rules)

    header = [
        f"# {category} — generated by hajimihomo",
        f"# behavior: {behavior}  rules: {len(deduped)}",
        "payload:",
    ]

    if behavior == "domain":
        body = _domain_payload(deduped)
    elif behavior == "ipcidr":
        body = _ipcidr_payload(deduped)
    else:
        body = _classical_payload(deduped)

    return "\n".join(header + body) + "\n"


def to_domain_yaml(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit a domain-behavior YAML containing only DOMAIN / DOMAIN-SUFFIX rules.

    Used to produce <Category>_Domain.yaml alongside a classical main file,
    giving users access to the efficient behavior:domain matching for the bulk
    of rules in mixed categories.
    """
    domain_rules = [(rt, v) for rt, v in rules if rt in DOMAIN_BEHAVIOR_TYPES]
    if not domain_rules:
        return ""
    deduped = _dedup(domain_rules)

    lines = [
        f"# {category} (domain only) — generated by hajimihomo",
        f"# behavior: domain  rules: {len(deduped)}",
        "payload:",
    ] + _domain_payload(deduped) + [""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Format helpers
# ---------------------------------------------------------------------------

def _domain_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:domain lines — bare or dot-prefixed."""
    lines = []
    for rt, v in rules:
        if rt == "DOMAIN":
            lines.append(f"  - '{v}'")
        else:  # DOMAIN-SUFFIX
            lines.append(f"  - '.{v}'")
    return lines


def _ipcidr_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:ipcidr lines — bare CIDR strings, no-resolve stripped."""
    lines = []
    for rt, v in rules:
        cidr = v.removesuffix(",no-resolve")
        lines.append(f"  - '{cidr}'")
    return lines


def _classical_payload(rules: list[tuple[str, str]]) -> list[str]:
    """behavior:classical lines — RULE_TYPE,VALUE format."""
    return [f"  - {rt},{v}" for rt, v in rules]
