"""
sing-box rule-set JSON emitter (version 3, ≥1.11.0).

Rule grouping:
  domain         → "domain"
  domain_suffix  → "domain_suffix"
  domain_keyword → "domain_keyword"
  domain_regex   → "domain_regex"
  ip_cidr        → "ip_cidr"  (IP-CIDR + IP-CIDR6; no-resolve flag stripped — sing-box handles DNS natively)
  process_name   → "process_name"

Note: IP-ASN is NOT supported in sing-box rule-set format; it is silently dropped.

Split files (emitted only for classical-behavior categories):
  .domain.json   — DOMAIN + DOMAIN-SUFFIX only
  .ip.json       — all IP-CIDR/IP-CIDR6 (no ip-resolve split; sing-box has no no-resolve concept)
  .residual.json — DOMAIN-KEYWORD + DOMAIN-REGEX (IP-ASN dropped)
  .process.json  — PROCESS-NAME only

Compile: `sing-box rule-set compile <file>.json`

Reference: https://sing-box.sagernet.org/configuration/rule-set/source-format/
"""

from __future__ import annotations
import json

_TYPE_MAP = {
    "DOMAIN": "domain",
    "DOMAIN-SUFFIX": "domain_suffix",
    "DOMAIN-KEYWORD": "domain_keyword",
    "DOMAIN-REGEX": "domain_regex",
    "IP-CIDR": "ip_cidr",
    "IP-CIDR6": "ip_cidr",
    "IP6-CIDR": "ip_cidr",
    "PROCESS-NAME": "process_name",
}

_FIELD_ORDER = ("domain", "domain_suffix", "domain_keyword", "domain_regex",
                "ip_cidr", "process_name")


def _build_json(rules: list[tuple[str, str]], category: str, comment: str = "") -> str:
    """
    Build a sing-box rule-set JSON for the given rules.
    Returns empty string if no supported rules exist after filtering.
    """
    buckets: dict[str, list[str]] = {}
    seen: set[tuple[str, str]] = set()

    for rule_type, value in rules:
        sb_key = _TYPE_MAP.get(rule_type)
        if sb_key is None:
            continue
        # Strip no-resolve flag from IP-CIDR values
        clean_value = value.split(",")[0] if "," in value else value
        item = (sb_key, clean_value)
        if item in seen:
            continue
        seen.add(item)
        buckets.setdefault(sb_key, []).append(clean_value)

    if not buckets:
        return ""

    rule_obj: dict[str, list[str]] = {}
    for key in _FIELD_ORDER:
        if key in buckets:
            rule_obj[key] = sorted(buckets[key])

    payload = {
        "$comment": comment or f"{category} — generated by hajimihomo",
        "version": 3,
        "rules": [rule_obj],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"


def to_json(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit sing-box rule-set JSON (version 3) with all supported rule types.
    IP-CIDR no-resolve flag is stripped (sing-box handles DNS internally).
    IP-ASN is silently dropped (not supported in sing-box rule-set format).
    """
    return _build_json(rules, category) or _empty_json(category)


def to_domain_json(rules: list[tuple[str, str]], category: str) -> str:
    """DOMAIN + DOMAIN-SUFFIX only. Returns empty string if none."""
    filtered = [(rt, v) for rt, v in rules if rt in ("DOMAIN", "DOMAIN-SUFFIX")]
    return _build_json(filtered, category, f"{category} (domain split) — generated by hajimihomo")


def to_ip_json(rules: list[tuple[str, str]], category: str) -> str:
    """
    All IP-CIDR/IP-CIDR6 rules. No-resolve flag stripped (sing-box has no equivalent).
    sing-box does not distinguish no-resolve vs resolve — one ip file covers all.
    Returns empty string if none.
    """
    filtered = [(rt, v) for rt, v in rules if rt in ("IP-CIDR", "IP-CIDR6", "IP6-CIDR")]
    return _build_json(filtered, category, f"{category} (ip split) — generated by hajimihomo")


def to_residual_json(rules: list[tuple[str, str]], category: str) -> str:
    """
    DOMAIN-KEYWORD + DOMAIN-REGEX only. IP-ASN is not supported in sing-box.
    Returns empty string if none.
    """
    filtered = [(rt, v) for rt, v in rules if rt in ("DOMAIN-KEYWORD", "DOMAIN-REGEX")]
    return _build_json(filtered, category, f"{category} (residual split) — generated by hajimihomo")


def to_process_json(rules: list[tuple[str, str]], category: str) -> str:
    """PROCESS-NAME only. Returns empty string if none."""
    filtered = [(rt, v) for rt, v in rules if rt == "PROCESS-NAME"]
    return _build_json(filtered, category, f"{category} (process split) — generated by hajimihomo")


def _empty_json(category: str) -> str:
    """Fallback empty rule-set (should not normally be needed)."""
    return json.dumps({
        "$comment": f"{category} — generated by hajimihomo",
        "version": 3,
        "rules": [{}],
    }, ensure_ascii=False, indent=2) + "\n"
