"""
sing-box rule-set JSON emitter (version 3, ≥1.11.0).

Rule grouping:
  domain         → "domain"
  domain_suffix  → "domain_suffix"
  domain_keyword → "domain_keyword"
  domain_regex   → "domain_regex"
  ip_cidr        → "ip_cidr"  (IP-CIDR + IP-CIDR6; no-resolve flag stripped — sing-box handles DNS natively)
  process_name   → "process_name"

sing-box automatically downgrades version if advanced features are not used.
Compile: `sing-box rule-set compile <file>.json`

Reference: https://sing-box.sagernet.org/configuration/rule-set/source-format/
"""

from __future__ import annotations
import json

_TYPE_MAP = {
    "DOMAIN": "domain",
    "DOMAIN-SUFFIX": "domain_suffix",
    "DOMAIN-KEYWORD": "domain_keyword",
    "DOMAIN-REGEX": "domain_regex",
    "IP-CIDR": "ip_cidr",
    "IP-CIDR6": "ip_cidr",
    "IP6-CIDR": "ip_cidr",
    "PROCESS-NAME": "process_name",
}


def to_json(rules: list[tuple[str, str]], category: str) -> str:
    """
    Emit sing-box rule-set JSON (version 3).
    Groups all rules into a single rule object; deduplicates per field.
    IP-CIDR no-resolve flag is stripped (sing-box handles DNS resolution internally).
    """
    buckets: dict[str, list[str]] = {}
    seen: set[tuple[str, str]] = set()

    for rule_type, value in rules:
        sb_key = _TYPE_MAP.get(rule_type)
        if sb_key is None:
            continue
        # strip no-resolve flag from IP-CIDR values
        clean_value = value.split(",")[0] if "," in value else value
        item = (sb_key, clean_value)
        if item in seen:
            continue
        seen.add(item)
        buckets.setdefault(sb_key, []).append(clean_value)

    rule_obj: dict[str, list[str]] = {}
    # canonical field order
    for key in ("domain", "domain_suffix", "domain_keyword", "domain_regex",
                "ip_cidr", "process_name"):
        if key in buckets:
            rule_obj[key] = sorted(buckets[key])

    payload = {
        "version": 3,
        "rules": [rule_obj] if rule_obj else [],
    }
    # metadata comment not possible in JSON; add a top-level field
    payload["$comment"] = f"{category} — generated by hajimihomo"

    return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
