# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Binance/README.md
name: Binance
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Binance.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Binance.yaml
  - https://github.com/StricklandF/Filter/blob/main/Binance.list
