# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Xunlei/README.md
name: Xunlei
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xunlei.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/XunLei.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Xunlei.yaml
