# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Marketing/README.md
name: Marketing
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Marketing.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Marketing.yaml
