# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ChinaMobile/README.md
name: ChinaMobile
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ChinaMobile.list
