# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HamiVideo/README.md
name: HamiVideo
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/HamiVideo.list
