# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/RemoteDesktop/README.md
name: RemoteDesktop
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/RemoteDesktop.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/RemoteDesktop.yaml
