# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Nvidia/README.md
name: Nvidia
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Nvidia.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Nvidia.yaml
