# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/NGA/README.md
name: NGA
sources:
  - https://raw.githubusercontent.com/ameyukisora/Clash-Rule/master/provider/nga.yaml
  - https://rules.kr328.app/nga.yaml
