# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/SystemOTA/README.md
name: SystemOTA
sources:
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/SystemOTA/SystemOTA.list
  - https://raw.githubusercontent.com/an0na/R/master/Filter/IOS_OTA.list
  - https://raw.githubusercontent.com/LuzMasonj/Quantumult/master/QuantumultX/Filter/BlockiOSServices.conf
