# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/KingSmith/README.md
name: KingSmith
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/KingSmith.list
