# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/YYeTs/README.md
name: YYeTs
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/YYeTs.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YYeTs.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YYeTs.yaml
