# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/WangSuKeJi/README.md
name: WangSuKeJi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/WangSuKeJi.list
