# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/4399/README.md
name: 4399
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/4399.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/4399.list
