# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/DtDNS/README.md
name: DtDNS
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/DtDNS.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/DtDNS.yaml
