# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ByteDance/README.md
name: ByteDance
sources:
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/ByteDance/ByteDance.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ByteDance.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ByteDance.list
  - https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Douyin.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/ByteDance.yaml
