# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Jfrog/README.md
name: Jfrog
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Jfrog.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Jfrog.yaml
