# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ZhongWeiShiJi/README.md
name: ZhongWeiShiJi
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/ZhongWeiShiJi.list
