import { loadCatalog, getGroups, buildMihomoGroups, buildSingboxRuleSets } from './ProfileBuilder.js'

const app = document.getElementById('app')

app.innerHTML = `
  <div class="section">
    <label>内核</label>
    <select id="kernel">
      <option value="mihomo">mihomo (Clash Meta)</option>
      <option value="singbox">sing-box</option>
    </select>
  </div>

  <div class="section">
    <label>规则集格式</label>
    <select id="tier">
      <option value="1">Tier 1 — 经典合并（兼容性最佳）</option>
      <option value="2">Tier 2 — 分离格式（域名/IP 分离，性能最优）</option>
    </select>
  </div>

  <div class="section">
    <label>预设</label>
    <select id="preset">
      <option value="minimal">minimal — 核心规则（广告屏蔽 + 常用代理）</option>
      <option value="full">full — 完整规则（流媒体 + 社交 + 游戏 + 开发工具）</option>
      <option value="custom">自定义</option>
    </select>
  </div>

  <div class="section">
    <label>订阅链接（每行一个）</label>
    <textarea id="subs" placeholder="https://your-subscription-url/..."></textarea>
  </div>

  <div class="section" id="cat-section" style="display:none">
    <label>规则集 <span id="cat-count" style="color:#8b949e"></span></label>
    <div class="categories-grid" id="cat-grid"></div>
  </div>

  <div style="margin-top:1.5rem">
    <button class="btn" id="generate">生成配置</button>
    <button class="btn btn-secondary" id="copy">复制</button>
  </div>

  <div id="output" class="output-block" style="display:none"></div>
`

// Catalog group IDs for presets
const PRESETS = {
  minimal: [
    'block/ads',
    'direct/cn',
    'proxy/apple',
    'proxy/google',
    'proxy/telegram',
    'proxy/youtube',
    'proxy/dev',
  ],
  full: [
    'block/ads',
    'block/tracking',
    'direct/cn',
    'direct/cn-ips',
    'proxy/google',
    'proxy/youtube',
    'proxy/apple',
    'proxy/microsoft',
    'proxy/amazon',
    'proxy/telegram',
    'proxy/twitter',
    'proxy/netflix',
    'proxy/streaming',
    'proxy/social',
    'proxy/ai',
    'proxy/gaming',
    'proxy/dev',
    'proxy/finance',
    'proxy/news',
  ],
}

let catalog = null
let selectedGroups = new Set(PRESETS.minimal)

async function init() {
  try {
    catalog = await loadCatalog()
    populateCatalogGrid(catalog)
  } catch (e) {
    console.warn('Could not load catalog:', e)
    catalog = { items: {} }
  }
}

function populateCatalogGrid(catalog) {
  const grid = document.getElementById('cat-grid')
  grid.innerHTML = ''
  const groups = getGroups(catalog)
  for (const group of groups) {
    const actionBadge = group.defaultAction === 'REJECT'
      ? '<span class="tag block">block</span>'
      : group.defaultAction === 'DIRECT'
        ? '<span class="tag direct">direct</span>'
        : '<span class="tag proxy">proxy</span>'
    const item = document.createElement('label')
    item.className = 'cat-item'
    item.innerHTML = `
      <input type="checkbox" value="${group.id}" ${selectedGroups.has(group.id) ? 'checked' : ''}>
      <span>${group.name}${actionBadge}</span>
    `
    item.querySelector('input').addEventListener('change', e => {
      if (e.target.checked) selectedGroups.add(group.id)
      else selectedGroups.delete(group.id)
      updateCatCount()
    })
    grid.appendChild(item)
  }
  updateCatCount()
}

function updateCatCount() {
  document.getElementById('cat-count').textContent = `(${selectedGroups.size} 已选)`
}

document.getElementById('preset').addEventListener('change', e => {
  const val = e.target.value
  const isCustom = val === 'custom'
  document.getElementById('cat-section').style.display = isCustom ? '' : 'none'
  if (!isCustom) {
    selectedGroups = new Set(PRESETS[val] || [])
    document.querySelectorAll('#cat-grid input[type="checkbox"]').forEach(cb => {
      cb.checked = selectedGroups.has(cb.value)
    })
    updateCatCount()
  }
})

document.getElementById('generate').addEventListener('click', () => {
  const kernel = document.getElementById('kernel').value
  const tier   = parseInt(document.getElementById('tier').value, 10)
  const preset = document.getElementById('preset').value
  const groupIds = preset === 'custom' ? [...selectedGroups] : (PRESETS[preset] || [])
  const subs = document.getElementById('subs').value.trim().split('\n').filter(Boolean)

  if (subs.length === 0) {
    alert('请至少输入一个订阅链接')
    return
  }

  const output = kernel === 'mihomo'
    ? generateMihomo(groupIds, subs, tier)
    : generateSingbox(groupIds, subs, tier)

  const el = document.getElementById('output')
  el.textContent = output
  el.style.display = 'block'
})

document.getElementById('copy').addEventListener('click', () => {
  const text = document.getElementById('output').textContent
  if (text) navigator.clipboard.writeText(text).then(() => alert('已复制'))
})

function generateMihomo(groupIds, subs, tier) {
  const { proxyProviders, groups, providers, rules } =
    buildMihomoGroups(subs, groupIds, catalog || { items: {} }, { tier })

  const lines = [
    '# generated by hajimihomo profile builder',
    `# tier: ${tier}  groups: ${groupIds.length}`,
    '',
    'proxy-providers:',
    ...Object.entries(proxyProviders).flatMap(([k, v]) => [
      `  ${k}:`,
      `    type: ${v.type}`,
      `    url: "${v.url}"`,
      `    interval: ${v.interval}`,
      `    health-check:`,
      `      enable: ${v.health_check.enable}`,
      `      url: "${v.health_check.url}"`,
      `      interval: ${v.health_check.interval}`,
    ]),
    '',
    'proxy-groups:',
    ...groups.flatMap(g => {
      const out = [`  - name: ${g.name}`, `    type: ${g.type}`]
      if (g.use)      out.push(`    use: [${g.use.join(', ')}]`)
      if (g.proxies)  out.push(`    proxies: [${g.proxies.join(', ')}]`)
      if (g.url)      out.push(`    url: "${g.url}"`, `    interval: ${g.interval}`)
      if (g.tolerance) out.push(`    tolerance: ${g.tolerance}`)
      return out
    }),
    '',
    'rule-providers:',
    ...Object.entries(providers).flatMap(([k, v]) => [
      `  ${k}:`,
      `    type: ${v.type}`,
      `    behavior: ${v.behavior}`,
      `    url: "${v.url}"`,
      `    path: "${v.path}"`,
      `    interval: ${v.interval}`,
    ]),
    '',
    'rules:',
    ...rules.map(r => `  - ${r}`),
    '  - GEOIP,CN,DIRECT',
    '  - MATCH,PROXY',
  ]
  return lines.join('\n')
}

function generateSingbox(groupIds, subs, tier) {
  // sing-box output is a route/rule_set fragment.
  // Subscription-based outbounds must be imported separately via the kernel.
  const { ruleSets, routeRules } =
    buildSingboxRuleSets(groupIds, catalog || { items: {} }, { tier })

  const outbounds = [
    { tag: 'proxy',   type: 'selector', outbounds: ['auto', 'direct'] },
    { tag: 'auto',    type: 'urltest',  outbounds: ['direct'],
      url: 'https://cp.cloudflare.com', interval: '5m' },
    { tag: 'direct',  type: 'direct' },
    { tag: 'block',   type: 'block' },
    { tag: 'dns-out', type: 'dns' },
  ]

  const config = {
    '$comment': `generated by hajimihomo profile builder — tier ${tier}`,
    outbounds,
    route: {
      rule_set: ruleSets,
      rules: [
        { protocol: 'dns', outbound: 'dns-out' },
        ...routeRules,
        { geoip: 'cn', outbound: 'direct' },
      ],
      final: 'proxy',
      auto_detect_interface: true,
    },
  }
  return JSON.stringify(config, null, 2)
}

init()
