import { loadCatalog, buildRuleProviders, buildMihomoGroups } from './ProfileBuilder.js'

const app = document.getElementById('app')

app.innerHTML = `
  <div class="section">
    <label>内核</label>
    <select id="kernel">
      <option value="mihomo">mihomo (Clash Meta)</option>
      <option value="singbox">sing-box</option>
    </select>
  </div>

  <div class="section">
    <label>预设</label>
    <select id="preset">
      <option value="minimal">minimal — 核心规则（广告屏蔽 + 常用代理）</option>
      <option value="full">full — 完整规则（流媒体 + 社交 + 游戏 + 开发工具）</option>
      <option value="custom">自定义</option>
    </select>
  </div>

  <div class="section">
    <label>订阅链接（每行一个）</label>
    <textarea id="subs" placeholder="https://your-subscription-url/..."></textarea>
  </div>

  <div class="section" id="cat-section" style="display:none">
    <label>规则集 <span id="cat-count" style="color:#8b949e"></span></label>
    <div class="categories-grid" id="cat-grid"></div>
  </div>

  <div style="margin-top:1.5rem">
    <button class="btn" id="generate">生成配置</button>
    <button class="btn btn-secondary" id="copy">复制</button>
  </div>

  <div id="output" class="output-block" style="display:none"></div>
`

const PRESETS = {
  minimal: ['Advertising', 'Privacy', 'China', 'Apple', 'Google', 'Telegram', 'YouTube', 'GitHub', 'Microsoft'],
  full: ['Advertising', 'Privacy', 'Hijacking', 'China', 'ChinaMedia', 'Microsoft', 'Apple',
    'Google', 'Telegram', 'YouTube', 'Twitter', 'Facebook', 'GitHub', 'GitLab',
    'Cloudflare', 'Amazon', 'Netflix', 'Disney', 'Spotify', 'TikTok', 'OpenAI',
    'Steam', 'PlayStation', 'Docker', 'Notion', 'Slack'],
}

let catalog = null
let selectedCats = new Set(PRESETS.minimal)

async function init() {
  try {
    catalog = await loadCatalog()
    populateCatalogGrid(catalog)
  } catch (e) {
    console.warn('Could not load catalog:', e)
    catalog = {}
  }
}

function populateCatalogGrid(catalog) {
  const grid = document.getElementById('cat-grid')
  grid.innerHTML = ''
  const all = Object.keys(catalog).sort()
  for (const cat of all) {
    const info = catalog[cat]
    const behaviorTag = info.behavior === 'domain' ? ''
      : info.behavior === 'ipcidr' ? '<span class="tag ip">ip</span>'
      : '<span class="tag mixed">mixed</span>'
    const item = document.createElement('label')
    item.className = 'cat-item'
    item.innerHTML = `
      <input type="checkbox" value="${cat}" ${selectedCats.has(cat) ? 'checked' : ''}>
      <span>${cat}${behaviorTag}</span>
    `
    item.querySelector('input').addEventListener('change', e => {
      if (e.target.checked) selectedCats.add(cat)
      else selectedCats.delete(cat)
      updateCatCount()
    })
    grid.appendChild(item)
  }
  updateCatCount()
}

function updateCatCount() {
  document.getElementById('cat-count').textContent = `(${selectedCats.size} 已选)`
}

document.getElementById('preset').addEventListener('change', e => {
  const val = e.target.value
  const isCustom = val === 'custom'
  document.getElementById('cat-section').style.display = isCustom ? '' : 'none'
  if (!isCustom) {
    selectedCats = new Set(PRESETS[val] || [])
    document.querySelectorAll('#cat-grid input[type="checkbox"]').forEach(cb => {
      cb.checked = selectedCats.has(cb.value)
    })
    updateCatCount()
  }
})

document.getElementById('generate').addEventListener('click', () => {
  const kernel = document.getElementById('kernel').value
  const preset = document.getElementById('preset').value
  const cats = preset === 'custom' ? [...selectedCats] : (PRESETS[preset] || [])
  const subs = document.getElementById('subs').value.trim().split('\n').filter(Boolean)

  if (subs.length === 0) {
    alert('请至少输入一个订阅链接')
    return
  }

  let output
  if (kernel === 'mihomo') {
    output = generateMihomo(cats, subs)
  } else {
    output = generateSingbox(cats, subs)
  }

  const el = document.getElementById('output')
  el.textContent = output
  el.style.display = 'block'
})

document.getElementById('copy').addEventListener('click', () => {
  const text = document.getElementById('output').textContent
  if (text) navigator.clipboard.writeText(text).then(() => alert('已复制'))
})

function generateMihomo(cats, subs) {
  const { proxyProviders, groups, rules } = buildMihomoGroups(subs, cats, catalog || {})
  const providers = buildRuleProviders(cats, catalog || {})

  // minimal YAML serialization (no external dep)
  const lines = [
    '# generated by hajimihomo profile builder',
    '# paste into your mihomo config or use as rule-providers fragment',
    '',
    'proxy-providers:',
    ...Object.entries(proxyProviders).flatMap(([k, v]) => [
      `  ${k}:`,
      `    type: ${v.type}`,
      `    url: "${v.url}"`,
      `    interval: ${v.interval}`,
      `    health-check:`,
      `      enable: ${v.health_check.enable}`,
      `      url: "${v.health_check.url}"`,
      `      interval: ${v.health_check.interval}`,
    ]),
    '',
    'proxy-groups:',
    ...groups.flatMap(g => {
      const lines = [`  - name: ${g.name}`, `    type: ${g.type}`]
      if (g.use) lines.push(`    use: [${g.use.join(', ')}]`)
      if (g.proxies) lines.push(`    proxies: [${g.proxies.join(', ')}]`)
      if (g.url) lines.push(`    url: "${g.url}"`, `    interval: ${g.interval}`)
      return lines
    }),
    '',
    'rule-providers:',
    ...Object.entries(providers).flatMap(([k, v]) => [
      `  ${k}:`,
      `    type: ${v.type}`,
      `    behavior: ${v.behavior}`,
      `    url: "${v.url}"`,
      `    path: "${v.path}"`,
      `    interval: ${v.interval}`,
    ]),
    '',
    'rules:',
    ...rules.map(r => `  - ${r}`),
  ]
  return lines.join('\n')
}

function generateSingbox(cats, subs) {
  // minimal sing-box fragment — outbounds + route rules
  const outbounds = [
    { tag: 'proxy', type: 'selector', outbounds: ['auto', 'direct'] },
    { tag: 'auto', type: 'urltest', outbounds: ['direct'], url: 'https://cp.cloudflare.com', interval: '5m' },
    { tag: 'direct', type: 'direct' },
    { tag: 'block', type: 'block' },
    { tag: 'dns-out', type: 'dns' },
  ]

  const ruleSets = cats.map(cat => ({
    tag: `ruleset-${cat}`,
    type: 'remote',
    format: 'binary',
    url: `https://github.com/cest-la-v/hajimihomo/releases/latest/download/${cat}.srs`,
    download_detour: 'proxy',
    update_interval: '1d',
  }))

  const BLOCK = new Set(['Advertising', 'Privacy', 'Hijacking'])
  const DIRECT = new Set(['China', 'ChinaMedia', 'Microsoft'])
  const routeRules = [
    { protocol: 'dns', outbound: 'dns-out' },
    ...cats.map(cat => ({
      rule_set: `ruleset-${cat}`,
      outbound: BLOCK.has(cat) ? 'block' : DIRECT.has(cat) ? 'direct' : 'proxy',
    })),
    { geoip: 'cn', outbound: 'direct' },
  ]

  const config = {
    '$comment': 'generated by hajimihomo profile builder',
    outbounds,
    route: {
      rule_set: ruleSets,
      rules: routeRules,
      final: 'proxy',
      auto_detect_interface: true,
    },
  }
  return JSON.stringify(config, null, 2)
}

init()
