# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/HuluJP/README.md
name: HuluJP
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Hulu.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/HuluJapan.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/HuluJapan.yaml
