# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Reddit/README.md
name: Reddit
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Reddit.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Reddit.yaml
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Reddit.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Reddit.yaml
