# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Stackexchange/README.md
name: Stackexchange
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Stackexchange.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Stackexchange.yaml
