# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Qobuz/README.md
name: Qobuz
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Qobuz.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Qobuz.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Qobuz.yaml
