# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TeraBox/README.md
name: TeraBox
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TeraBox.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/TeraBox.yaml
