# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/TongCheng/README.md
name: TongCheng
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic-Services/TongCheng.list
