# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Americasvoice/README.md
name: Americasvoice
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Americasvoice.list
