# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/VikACG/README.md
name: VikACG
sources:
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/VikACG.list
  - https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/VikACG.yaml
