# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/MOMOShop/README.md
name: MOMOShop
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/momoshop.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/momoshop.yaml
