# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/AppleProxy/README.md
name: AppleProxy
sources:
  - https://raw.githubusercontent.com/Hackl0us/SS-Rule-Snippet/master/Rulesets/Surge/Basic/Apple-proxy.list
  - https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/source/rule/AppleBlock/AppleBlock.list
