# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Jwplayer/README.md
name: Jwplayer
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Jwplayer.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Jwplayer.yaml
