# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/Sling/README.md
name: Sling
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Sling.list
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Sling.yaml
