# Auto-extracted from blackmatrix7/ios_rule_script rule/Clash/ATTWatchTV/README.md
name: ATTWatchTV
sources:
  - https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/ATTWatchTV.list
